Updated logging boilerplate

diff --git a/battery/notifications b/battery/notifications
--- a/battery/notifications
+++ b/battery/notifications
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+# fail on error
+
+set -o errexit
+set -o pipefail
+set -o nounset
+
+# get file name
+
+__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
+__logfile=$__file.log
+
+# set up logging
+
+exec 3>&1 4>&2
+trap 'exec 2>&4 1>&3' 0 1 2 3
+exec 1>$__logfile 2>&1
+
+# everything below will be sent to a log file
+
+
 # if the battery % is below 10%
 # and the laptop is not plugged in,
 # then send a notification every minute
@@ -39,8 +60,13 @@ while true
 do
 	# export DISPLAY=:0.0
 
-	status=$(acpi -b | grep -P -o '(?<=\:)(.*?)(?=,)' | tr -d '[:space:]')
-	battery=$(acpi -b | grep -P -o '[0-9]+(?=%)')
+	# instead of acpi use
+	# cat /sys/class/power_supply/BAT?/capacity
+	# or
+	# cat /sys/class/power_supply/BAT0/capacity
+
+	status=$(acpi -b | grep "Battery 0" | grep -P -o '(?<=\:)(.*?)(?=,)' | tr -d '[:space:]')
+	battery=$(acpi -b | grep "Battery 0" | grep -P -o '[0-9]+(?=%)')
 
 	echo "status:		$status"
 	echo "battery:	$battery"
